### PR TITLE
Deprecate UnkwnownCommandError

### LINKED ISSUE #35: Typo in UnkwnownCommandError class name
Class should be named `UnknownCommandError` instead

### PR DESCRIPTION
**Pull request by d4rky-pl**
Fixes #35

### CODE REVIEW

**Comment by davydovanton** [comment]
also, could you fix rubocop warning?

**Comment by d4rky-pl** [comment]
@davydovanton done, though now I'm starting to consider moving the `const_missing` from `cli/errors` to `cli`. What do you think?

**Comment by d4rky-pl** [comment]
@AlfonsoUceda would you kindly review again? :)

**Comment by AlfonsoUceda** [comment]
thanks @d4rky-pl mergint it.

**Pull request merged**
