### PR TITLE
Add --[no-]skip-git option to `hanami new` command

### PR DESCRIPTION
**Pull request by vikdotdev**
We can consider adding `.gitignore` but I don't really see anything worth ignoring by default in `2.0.0.beta2`.

### CODE REVIEW

**Comment by vikdotdev** [comment]
My first PR here. I have trouble running specs on local machine. Everything seems to point to issue with an undefined method from routes gem. I can see that it exists at [hanami/router](https://github.com/hanami/router/blob/062f5bb7b2d3ff0d9172cffb8de7fc8b1b51da61/lib/hanami/router.rb#L48). Any idea why that might be?
```
     Failure/Error:
       define do
         get "/", to: "home.index"
         get "/about", to: "home.about"
       end

     NoMethodError:
       undefined method `define' for Test::Routes:Class
       Did you mean?  defined?
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami/routes.rb:72:in `method_missing'
     # ./spec/fixtures/test/config/routes.rb:7:in `<class:Routes>'
     # ./spec/fixtures/test/config/routes.rb:6:in `<module:Test>'
     # ./spec/fixtures/test/config/routes.rb:5:in `<top (required)>'
     # /home/vik/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
     # /home/vik/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami/slice.rb:377:in `load_routes'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami/slice.rb:184:in `routes'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami/slice.rb:334:in `prepare_container_providers'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami/slice.rb:269:in `prepare_all'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami/app.rb:129:in `prepare_all'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami/slice.rb:218:in `prepare_slice'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami/slice.rb:90:in `prepare'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami.rb:102:in `prepare'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/hanami-3724854e4290/lib/hanami/prepare.rb:5:in `<top (required)>'
     # /home/vik/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
     # /home/vik/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
     # ./lib/hanami/cli/commands/app/command.rb:33:in `app'
     # ./lib/hanami/cli/commands/app/generate/action.rb:47:in `call'
     # ./lib/hanami/cli/commands/app/command.rb:21:in `call'
     # ./spec/unit/hanami/cli/commands/app/generate/action_spec.rb:22:in `block (4 levels) in <top (required)>'
     # ./spec/unit/hanami/cli/commands/app/generate/action_spec.rb:442:in `block in within_application_directory'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/dry-files-c1003b56e1eb/lib/dry/files/memory_file_system.rb:188:in `chdir'
     # /home/vik/.rvm/gems/ruby-3.1.2/bundler/gems/dry-files-c1003b56e1eb/lib/dry/files.rb:148:in `chdir'
     # ./spec/unit/hanami/cli/commands/app/generate/action_spec.rb:425:in `within_application_directory'
     # ./spec/unit/hanami/cli/commands/app/generate/action_spec.rb:21:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:63:in `block (2 levels) in <top (required)>'
```

**Comment by cllns** [comment]
@vikdotdev If you pull my changes in from https://github.com/hanami/cli/pull/46, the specs should work again :)

**Comment by solnic** [comment]
I just merged in #46 to main so please rebase your branch. There are some specs failing because we're updating CLI to work with improved Routes DSL that no longer needs `define do ... end` block.

**Comment by vikdotdev** [comment]
Tests now work after rebase. Thank you! 

I was not entirely convinced it would run the command in the correct folder so I did a manual smoke test and it seems to work alright.

**Review by jodosha — COMMENTED** [review]
@vikdotdev Thanks for this PR, ATM we don't initialize a Git repository.
Any reason why we should start doing?

**Comment by vikdotdev** [comment]
Hey @jodosha

>  Any reason why we should start doing?

Hanami v1.3.x does that and I couldn't find why it was removed from the v2.0.0. Also, I imagine a lot of frameworks do that as a small improvement for developer experience.

If Hanami is more of a DIY as opposed to batteries-included (which it is, at least compared to Rails) I don't see it as a detriment to the framework if this wasn't included.

**Comment by jodosha** [comment]
@vikdotdev Thank you, but we aren't 100% sure about this enhancement. Marked for future consideration. Thanks. 🙏

**Pull request closed without merging**
