### PR TITLE
Use new asset tags in templates

### LINKED ISSUE #120: `hanami new` generates incorrect layout, crashing on helpers call
### Background

Version: v2.1.0-rc1

When you try to generate a new app using hanami/cli, application will crash due to the incorrect helper names in the layout .

### Steps to reproduce

```ruby
gem install hanami --pre
hanami new sandbox && cd sandbox
hanami g slice main
hanami g action home.show --slice="Main"
bundle exec hanami server
# visit localhost:2300/main/home/1
```

Application crashes due to `favicon`, `css` and `js` methods in the `layouts/app.html.erb` not being found

image

### PR DESCRIPTION
**Pull request by olivierlacan**
Fixes #120

### CODE REVIEW

**Comment by olivierlacan** [comment]
Oops, missed #121. My bad.

**Comment by timriley** [comment]
Thanks for putting this together, though, @olivierlacan!

Since these couple of hitches are getting in the way of people properly testing our release candidate, my plan is for us to make an rc2 release in the next day or two, just so that people can give things a proper try :)

**Comment by olivierlacan** [comment]
@timriley Sounds great, switched to tracking main for now since I’m experimenting anyway. ☺️

**Comment by jodosha** [comment]
@olivierlacan Thanks for opening this PR, regardless. ❤️

**Pull request closed without merging**
